### PR TITLE
Removed commented css

### PR DESCRIPTION
**Pull request by shngt**
Removed commented css and empty classes. Related to issue #3

### CODE REVIEW

**Comment by shngt** [comment]
@cTxplorer could you please review?

**Comment by cTxplorer** [comment]
@shngt thanks for raising the PR
Just curious - did you cross-checked if there's any class style defined in CSS, but the class isn't ever used in html?

**Comment by shngt** [comment]
Ah no, I haven't. Will do

**Comment by shngt** [comment]
Umm so I don't see an element with the fas class in the footer - would that make "footer .fas" irrelevant? Rest seems relevant to me

**Comment by cTxplorer** [comment]
LGTM, thanks for the PR @shngt ! 

Please feel free to squash bugs that you think should be fixed or improvements that can be made.

**Comment by shngt** [comment]
Sure, thank you!

**Pull request merged**
